# Generated by Django 3.2.5 on 2022-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojo_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=50)),
                ('No_of_stocks_above_200_EMA', models.IntegerField(default=0)),
                ('percentage_of_stocks_above_200_EMA', models.FloatField(default=0)),
                ('No_of_stocks_above_100_EMA', models.IntegerField(default=0)),
                ('percentage_of_stocks_above_100_EMA', models.FloatField(default=0)),
                ('No_of_stocks_above_50_EMA', models.IntegerField(default=0)),
                ('percentage_of_stocks_above_50_EMA', models.FloatField(default=0)),
            ],
        ),
    ]
